version: '3.7'

services:
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENERS: OUTSIDE://:29092, INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:29092, INSIDE://:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on: 
      - zookeeper
    ports:
      - target: 29092
        published: 29092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  authAll:
    image: zolotas4/typhon-analytics-auth-all
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - target: 2181
        published: 2181
  taskmanager:
    image: flink:latest
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    depends_on: 
      - jobmanager
    command: taskmanager
    expose:
      - 6121
      - 6122
  jobmanager:
    image: flink:latest
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    ports:
      - target: 8081
        published: 8081
    command: jobmanager
    expose:
      - 6123

