version: '3.7'

services:
  appdata:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: zcRMpfw8dJSFa94I
  vehicledatadb:
    image: mongo:latest
    command: mongod --replSet vehicledatadbReplset
  vehicledatadb-replica1:
    image: mongo:latest
    command: mongod --replSet vehicledatadbReplset
  vehicledatadb-replica2:
    image: mongo:latest
    command: mongod --replSet vehicledatadbReplset
  vehicledatadb-replica3:
    image: mongo:latest
    command: mongod --replSet vehicledatadbReplset
  vehicledatadb-rsinit:
    build:
      context: .
      dockerfile: vehicledatadb/rsinit
    entrypoint: [
      'sh', 
      '-c', 
      'init_set.sh'
      ]
      
  textwarningdata:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: meAgain
      MONGO_INITDB_ROOT_PASSWORD: qq9avNFBCZGQ6QjT
    ports:
      - target: 27017
        published: 27017
  vehiclemetadatadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Z6SA8eEVBPi9nKuW
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  polystore-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 7Mq1XHQHhC0C2dEp
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./models/:/docker-entrypoint-initdb.d
  typhon-polystore-service:
    image: clms/typhon-polystore-api:latest
    ports:
      - target: 8080
        published: 8080
    entrypoint:
      - wait-for-it
      - polystore-mongo:27017
      - -t
      - '60'
      - --
      - java
      - -cp
      - /app/resources:/app/classes:/app/libs/*
      - com.clms.typhonapi.Application
    restart: always
  polystore-ui:
    image: clms/typhon-polystore-ui:latest
    environment:
      API_PORT: 8080
      API_HOST: localhost
    depends_on: 
      - typhon-polystore-service
    ports:
      - target: 4200
        published: 4200
  typhonql-server:
    image: swatengineering/typhonql-server
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - target: 2181
        published: 2181
  kafka:
    
    depends_on: 
      - zookeeper
    ports:
      - target: 32100
        published: 29092
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  authAll:
    image: zolotas4/typhon-analytics-auth-all
