version: '3.7'

services:
  vehicledatadb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: me
      MONGO_INITDB_ROOT_PASSWORD: h0tcJ86u13c5LSrs
  appdata:
    image: mariadb:latest
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: M3XW1DnE8KUhzslv
  textwarningdata:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: me
      MONGO_INITDB_ROOT_PASSWORD: 3RqVuEj5jLjl5wB7
  polystore-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: h5XOPQKoXDZUxnuP
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./models/:/docker-entrypoint-initdb.d
  typhon-polystore-service:
    image: clms/typhon-polystore-api:latest
    ports:
      - target: 8080
        published: 8080
    entrypoint:
      - wait-for-it
      - polystore-mongo:27017
      - -t
      - '60'
      - --
      - java
      - -cp
      - /app/resources:/app/classes:/app/libs/*
      - com.clms.typhonapi.Application
    restart: always
  polystore-ui:
    image: clms/typhon-polystore-ui:latest
    environment:
      API_PORT: 8080
      API_HOST: localhost
    depends_on: 
      - typhon-polystore-service
    ports:
      - target: 4200
        published: 4200
  typhonql-server:
    image: swatengineering/typhonql-server
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - target: 2181
        published: 2181
  kafka:
    
    depends_on: 
      - zookeeper
    ports:
      - target: 32100
        published: 29092
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  authAll:
    image: zolotas4/typhon-analytics-auth-all
