version: '3.7'

services:
  polystore_api:
    image: clms/typhon-polystore-api:latest
    restart: always
    hostname: polystore_api
    depends_on: 
      - polystoredb
    container_name: typhonml.polystore.service
    ports:
      - 8080:8080
    volumes:
      - ./models:/models
  polystore_ui:
    image: clms/typhon-polystore-ui:latest
    restart: always
    hostname: polystore_ui
    depends_on: 
      - polystore_api
    container_name: polystore.ui
    ports:
      - 4200:4200
  polystoredb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: polystore.mongo
    ports:
      - 27017:27017
  TextWarningData:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
  AppData:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
