version: '3.7'

services:
  AppData:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - target: 3306
  VehicleMetadataDB:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - target: 3306
  TextWarningData:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - target: 27017
  VehicleDataDB:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - target: 27017
  polystore-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - target: 27017
    volumes:
      - ./models/:/docker-entrypoint-initdb.d
  typhon-polystore-service:
    image: clms/typhon-polystore-api:latest
    depends_on: 
      - polystore-mongo
    ports:
      - target: 8080
        published: 8080
  polystore-ui:
    image: clms/typhon-polystore-ui:latest
    environment:
      API_PORT: 8080
      API_HOST: localhost
    depends_on: 
      - typhon-polystore-service
    ports:
      - target: 4200
        published: 4200
  typhonql-server:
    image: swatengineering/typhonql-server
    ports:
      - target: 7000
