apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database-textwarningdata-deployment
  labels:
    app: user-database-textwarningdata-pod
spec:
  selector:
    matchLabels:
      app: user-database-textwarningdata-pod
  template:
    metadata:
      labels:
        app: user-database-textwarningdata-pod
    spec:
      containers:
        - name: textwarningdata
          image: mongo:latest
          ports:
            - containerPort: 27018          
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database-appdata-deployment
  labels:
    app: user-database-appdata-pod
spec:
  selector:
    matchLabels:
      app: user-database-appdata-pod
  template:
    metadata:
      labels:
        app: user-database-appdata-pod
    spec:
      containers:
        - name: appdata
          image: mariadb:latest
          ports:
            - containerPort: 3306          
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
---
apiVersion: v1
kind: Service
metadata:
  name: user-database-textwarningdata
  labels:
    app: user-database-textwarningdata
spec:
  type: NodePort
  ports:
    - name: "27018"
      port: 27018
      targetPort: 27018
  selector:
    app: user-database-textwarningdata-pod
---
apiVersion: v1
kind: Service
metadata:
  name: user-database-appdata
  labels:
    app: user-database-appdata
spec:
  type: NodePort
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: user-database-appdata-pod