apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: NodePort
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
spec:
  ports:
  - name: "54"
    port: 54
    targetPort: 80
  selector:
    io.kompose.service: phpmyadmin
  type: NodePort
status:
  loadBalancer: {}
