apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: sqldb
  name: sqldb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sqldb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: registration
        - name: MYSQL_PASSWORD
          value: desai
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: nisha
        image: mysql:5
        name: sqldb
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
