version: '3.7'

services:
  polystore_api:
    image: clms/typhon-polystore-api:latest
    restart: always
    hostname: polystore_api
    
    depends_on: 
      - polystoredb
    container_name: typhonml.polystore.service
    ports:
      -8080:8080
    volumes:
      -./models:/models
  polystore_ui:
    image: clms/typhon-polystore-ui:latest
    restart: always
    hostname: polystore_ui
    
    depends_on: 
      - polystore_api
    container_name: polystore.ui
    ports:
      -4200:4200
  polystoredb:
    image: mongo:latest
    
    container_name: polystore.mongo
    ports:
      -27017:27017
  zookeeper:
    image: wurstmeister/zookeeper
    
    container_name: zookeeper
    ports:
      -2181:2181
    networks:
      -typhon
  kafka:
    depends_on: 
      - zookeeper
    container_name: kafka
    ports:
      -9092:9092
    networks:
      -typhon
    volumes:
      -/var/run/docker.sock:/var/run/docker.sock
  productdb:
    image: mariadbimage
    
  orderdb:
    image: mongoimage
    
  userdb:
    image: mariadbimage
    
