version: '3.7'

services:
  vehicledatadb:
    image: mongo:latest
    command: mongod --replSet vehicledatadbReplset
  vehicledatadb-replica1:
    image: mongo:latest
    command: mongod --replSet vehicledatadbReplset
  vehicledatadb-replica2:
    image: mongo:latest
    command: mongod --replSet vehicledatadbReplset
  vehicledatadb-replica3:
    image: mongo:latest
    command: mongod --replSet vehicledatadbReplset
  vehicledatadb-rsinit:
    build:
      context: .
      dockerfile: vehicledatadb/rsinit
    entrypoint: [
      'sh', 
      '-c', 
      'init_set.sh'
      ]
      
  vehiclemetadatadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: hq50TzBAbJLK3mfR
    ports:
      - target: 3306
        published: 3306
  textwarningdata:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: me
      MONGO_INITDB_ROOT_PASSWORD: QR5IgggCPsAJaDo6
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  appdata:
    image: mariadb:latest
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: crwxlFQZ6N0MXUzS
  polystore-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./models/:/docker-entrypoint-initdb.d
  typhon-polystore-service:
    image: clms/typhon-polystore-api:latest
    ports:
      - target: 8080
        published: 8080
    entrypoint:
      - wait-for-it
      - polystore-mongo:27017
      - -t
      - '60'
      - --
      - java
      - -cp
      - /app/resources:/app/classes:/app/libs/*
      - com.clms.typhonapi.Application
    restart: always
  polystore-ui:
    image: clms/typhon-polystore-ui:latest
    environment:
      API_PORT: 8080
      API_HOST: localhost
    depends_on: 
      - typhon-polystore-service
    ports:
      - target: 4200
        published: 4200
  typhonql-server:
    image: swatengineering/typhonql-server
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - target: 2181
        published: 2181
  kafka:
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENERS: OUTSIDE://:29092, INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:29092, INSIDE://:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on: 
      - zookeeper
    ports:
      - target: 29092
        published: 29092
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jobmanager:
    image: flink:latest
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    ports:
      - target: 8081
        published: 8081
    command: jobmanager
    expose:
      - 6123
  taskmanager:
    image: flink:latest
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    depends_on: 
      - jobmanager
    command: taskmanager
    expose:
      - 6121
      - 6122
  authAll:
    image: zolotas4/typhon-analytics-auth-all
