/**
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.typhonDL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DB Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.typhon.dsls.xtext.typhonDL.TyphonDLPackage#getDBType()
 * @model
 * @generated
 */
public interface DBType extends Type
{
} // DBType
