/**
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.typhonDL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Env List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.typhon.dsls.xtext.typhonDL.EnvList#getEnvironmentVars <em>Environment Vars</em>}</li>
 * </ul>
 *
 * @see org.typhon.dsls.xtext.typhonDL.TyphonDLPackage#getEnvList()
 * @model
 * @generated
 */
public interface EnvList extends Property
{
  /**
   * Returns the value of the '<em><b>Environment Vars</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Environment Vars</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Environment Vars</em>' attribute list.
   * @see org.typhon.dsls.xtext.typhonDL.TyphonDLPackage#getEnvList_EnvironmentVars()
   * @model unique="false"
   * @generated
   */
  EList<String> getEnvironmentVars();

} // EnvList
