/**
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.typhonDL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Platform</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.typhon.dsls.xtext.typhonDL.Platform#getType <em>Type</em>}</li>
 *   <li>{@link org.typhon.dsls.xtext.typhonDL.Platform#getClusters <em>Clusters</em>}</li>
 * </ul>
 *
 * @see org.typhon.dsls.xtext.typhonDL.TyphonDLPackage#getPlatform()
 * @model
 * @generated
 */
public interface Platform extends Deployment
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(PlatformType)
   * @see org.typhon.dsls.xtext.typhonDL.TyphonDLPackage#getPlatform_Type()
   * @model
   * @generated
   */
  PlatformType getType();

  /**
   * Sets the value of the '{@link org.typhon.dsls.xtext.typhonDL.Platform#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(PlatformType value);

  /**
   * Returns the value of the '<em><b>Clusters</b></em>' containment reference list.
   * The list contents are of type {@link org.typhon.dsls.xtext.typhonDL.Cluster}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Clusters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clusters</em>' containment reference list.
   * @see org.typhon.dsls.xtext.typhonDL.TyphonDLPackage#getPlatform_Clusters()
   * @model containment="true"
   * @generated
   */
  EList<Cluster> getClusters();

} // Platform
