/**
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.typhonDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.typhon.dsls.xtext.typhonDL.TyphonDLPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
} // Property
