/**
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.typhonDL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.typhon.dsls.xtext.typhonDL.TyphonDLFactory
 * @model kind="package"
 * @generated
 */
public interface TyphonDLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "typhonDL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.typhon.org/dsls/xtext/TyphonDL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "typhonDL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TyphonDLPackage eINSTANCE = org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DeploymentModelImpl <em>Deployment Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.DeploymentModelImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDeploymentModel()
   * @generated
   */
  int DEPLOYMENT_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Deployment Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.TypeImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.DataTypeImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.PlatformTypeImpl <em>Platform Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.PlatformTypeImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getPlatformType()
   * @generated
   */
  int PLATFORM_TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLATFORM_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Platform Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLATFORM_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DBTypeImpl <em>DB Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.DBTypeImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDBType()
   * @generated
   */
  int DB_TYPE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>DB Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DeploymentImpl <em>Deployment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.DeploymentImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDeployment()
   * @generated
   */
  int DEPLOYMENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Deployment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.PlatformImpl <em>Platform</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.PlatformImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getPlatform()
   * @generated
   */
  int PLATFORM = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLATFORM__NAME = DEPLOYMENT__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLATFORM__TYPE = DEPLOYMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Clusters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLATFORM__CLUSTERS = DEPLOYMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Platform</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLATFORM_FEATURE_COUNT = DEPLOYMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.ClusterImpl <em>Cluster</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.ClusterImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getCluster()
   * @generated
   */
  int CLUSTER = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER__NAME = DEPLOYMENT__NAME;

  /**
   * The feature id for the '<em><b>Applications</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER__APPLICATIONS = DEPLOYMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cluster</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER_FEATURE_COUNT = DEPLOYMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.ApplicationImpl <em>Application</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.ApplicationImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getApplication()
   * @generated
   */
  int APPLICATION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION__NAME = DEPLOYMENT__NAME;

  /**
   * The feature id for the '<em><b>Containers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION__CONTAINERS = DEPLOYMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Application</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_FEATURE_COUNT = DEPLOYMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.ContainerImpl <em>Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.ContainerImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getContainer()
   * @generated
   */
  int CONTAINER = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__NAME = DEPLOYMENT__NAME;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__PROPERTIES = DEPLOYMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__FEATURES = DEPLOYMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_FEATURE_COUNT = DEPLOYMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.ServiceImpl <em>Service</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.ServiceImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getService()
   * @generated
   */
  int SERVICE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__NAME = DEPLOYMENT__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__FEATURES = DEPLOYMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Service</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_FEATURE_COUNT = DEPLOYMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DBServiceImpl <em>DB Service</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.DBServiceImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDBService()
   * @generated
   */
  int DB_SERVICE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB_SERVICE__NAME = SERVICE__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB_SERVICE__FEATURES = SERVICE__FEATURES;

  /**
   * The number of structural features of the '<em>DB Service</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DB_SERVICE_FEATURE_COUNT = SERVICE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.BusinessServiceImpl <em>Business Service</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.BusinessServiceImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getBusinessService()
   * @generated
   */
  int BUSINESS_SERVICE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUSINESS_SERVICE__NAME = SERVICE__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUSINESS_SERVICE__FEATURES = SERVICE__FEATURES;

  /**
   * The number of structural features of the '<em>Business Service</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUSINESS_SERVICE_FEATURE_COUNT = SERVICE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.EntityImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__SUPER_TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__FEATURES = TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.PropertyImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 14;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.EnvListImpl <em>Env List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.EnvListImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getEnvList()
   * @generated
   */
  int ENV_LIST = 15;

  /**
   * The feature id for the '<em><b>Environment Vars</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENV_LIST__ENVIRONMENT_VARS = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Env List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENV_LIST_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.AssignmentListImpl <em>Assignment List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.AssignmentListImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getAssignmentList()
   * @generated
   */
  int ASSIGNMENT_LIST = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_LIST__NAME = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Assignments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_LIST__ASSIGNMENTS = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Assignment List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_LIST_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.CommaSeparatedAssignmentListImpl <em>Comma Separated Assignment List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.CommaSeparatedAssignmentListImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getCommaSeparatedAssignmentList()
   * @generated
   */
  int COMMA_SEPARATED_ASSIGNMENT_LIST = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMA_SEPARATED_ASSIGNMENT_LIST__NAME = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMA_SEPARATED_ASSIGNMENT_LIST__VALUE = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMA_SEPARATED_ASSIGNMENT_LIST__VALUES = PROPERTY_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comma Separated Assignment List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMA_SEPARATED_ASSIGNMENT_LIST_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.AssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.AssignmentImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getAssignment()
   * @generated
   */
  int ASSIGNMENT = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__NAME = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__VALUE = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.typhon.dsls.xtext.typhonDL.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.typhon.dsls.xtext.typhonDL.impl.FeatureImpl
   * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.DeploymentModel <em>Deployment Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deployment Model</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.DeploymentModel
   * @generated
   */
  EClass getDeploymentModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.typhon.dsls.xtext.typhonDL.DeploymentModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.DeploymentModel#getElements()
   * @see #getDeploymentModel()
   * @generated
   */
  EReference getDeploymentModel_Elements();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.typhon.dsls.xtext.typhonDL.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.PlatformType <em>Platform Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Platform Type</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.PlatformType
   * @generated
   */
  EClass getPlatformType();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.DBType <em>DB Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DB Type</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.DBType
   * @generated
   */
  EClass getDBType();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Deployment <em>Deployment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deployment</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Deployment
   * @generated
   */
  EClass getDeployment();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Platform <em>Platform</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Platform</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Platform
   * @generated
   */
  EClass getPlatform();

  /**
   * Returns the meta object for the reference '{@link org.typhon.dsls.xtext.typhonDL.Platform#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Platform#getType()
   * @see #getPlatform()
   * @generated
   */
  EReference getPlatform_Type();

  /**
   * Returns the meta object for the containment reference list '{@link org.typhon.dsls.xtext.typhonDL.Platform#getClusters <em>Clusters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clusters</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Platform#getClusters()
   * @see #getPlatform()
   * @generated
   */
  EReference getPlatform_Clusters();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Cluster <em>Cluster</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cluster</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Cluster
   * @generated
   */
  EClass getCluster();

  /**
   * Returns the meta object for the containment reference list '{@link org.typhon.dsls.xtext.typhonDL.Cluster#getApplications <em>Applications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Applications</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Cluster#getApplications()
   * @see #getCluster()
   * @generated
   */
  EReference getCluster_Applications();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Application <em>Application</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Application
   * @generated
   */
  EClass getApplication();

  /**
   * Returns the meta object for the containment reference list '{@link org.typhon.dsls.xtext.typhonDL.Application#getContainers <em>Containers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Containers</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Application#getContainers()
   * @see #getApplication()
   * @generated
   */
  EReference getApplication_Containers();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Container <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Container
   * @generated
   */
  EClass getContainer();

  /**
   * Returns the meta object for the containment reference list '{@link org.typhon.dsls.xtext.typhonDL.Container#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Container#getProperties()
   * @see #getContainer()
   * @generated
   */
  EReference getContainer_Properties();

  /**
   * Returns the meta object for the containment reference list '{@link org.typhon.dsls.xtext.typhonDL.Container#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Container#getFeatures()
   * @see #getContainer()
   * @generated
   */
  EReference getContainer_Features();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Service <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Service
   * @generated
   */
  EClass getService();

  /**
   * Returns the meta object for the containment reference list '{@link org.typhon.dsls.xtext.typhonDL.Service#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Service#getFeatures()
   * @see #getService()
   * @generated
   */
  EReference getService_Features();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.DBService <em>DB Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DB Service</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.DBService
   * @generated
   */
  EClass getDBService();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.BusinessService <em>Business Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Business Service</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.BusinessService
   * @generated
   */
  EClass getBusinessService();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the reference '{@link org.typhon.dsls.xtext.typhonDL.Entity#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Entity#getSuperType()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link org.typhon.dsls.xtext.typhonDL.Entity#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Entity#getFeatures()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Features();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.EnvList <em>Env List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Env List</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.EnvList
   * @generated
   */
  EClass getEnvList();

  /**
   * Returns the meta object for the attribute list '{@link org.typhon.dsls.xtext.typhonDL.EnvList#getEnvironmentVars <em>Environment Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Environment Vars</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.EnvList#getEnvironmentVars()
   * @see #getEnvList()
   * @generated
   */
  EAttribute getEnvList_EnvironmentVars();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.AssignmentList <em>Assignment List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment List</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.AssignmentList
   * @generated
   */
  EClass getAssignmentList();

  /**
   * Returns the meta object for the attribute '{@link org.typhon.dsls.xtext.typhonDL.AssignmentList#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.AssignmentList#getName()
   * @see #getAssignmentList()
   * @generated
   */
  EAttribute getAssignmentList_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.typhon.dsls.xtext.typhonDL.AssignmentList#getAssignments <em>Assignments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Assignments</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.AssignmentList#getAssignments()
   * @see #getAssignmentList()
   * @generated
   */
  EReference getAssignmentList_Assignments();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.CommaSeparatedAssignmentList <em>Comma Separated Assignment List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comma Separated Assignment List</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.CommaSeparatedAssignmentList
   * @generated
   */
  EClass getCommaSeparatedAssignmentList();

  /**
   * Returns the meta object for the attribute '{@link org.typhon.dsls.xtext.typhonDL.CommaSeparatedAssignmentList#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.CommaSeparatedAssignmentList#getName()
   * @see #getCommaSeparatedAssignmentList()
   * @generated
   */
  EAttribute getCommaSeparatedAssignmentList_Name();

  /**
   * Returns the meta object for the attribute '{@link org.typhon.dsls.xtext.typhonDL.CommaSeparatedAssignmentList#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.CommaSeparatedAssignmentList#getValue()
   * @see #getCommaSeparatedAssignmentList()
   * @generated
   */
  EAttribute getCommaSeparatedAssignmentList_Value();

  /**
   * Returns the meta object for the attribute list '{@link org.typhon.dsls.xtext.typhonDL.CommaSeparatedAssignmentList#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.CommaSeparatedAssignmentList#getValues()
   * @see #getCommaSeparatedAssignmentList()
   * @generated
   */
  EAttribute getCommaSeparatedAssignmentList_Values();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Assignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Assignment
   * @generated
   */
  EClass getAssignment();

  /**
   * Returns the meta object for the attribute '{@link org.typhon.dsls.xtext.typhonDL.Assignment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Assignment#getName()
   * @see #getAssignment()
   * @generated
   */
  EAttribute getAssignment_Name();

  /**
   * Returns the meta object for the attribute '{@link org.typhon.dsls.xtext.typhonDL.Assignment#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Assignment#getValue()
   * @see #getAssignment()
   * @generated
   */
  EAttribute getAssignment_Value();

  /**
   * Returns the meta object for class '{@link org.typhon.dsls.xtext.typhonDL.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link org.typhon.dsls.xtext.typhonDL.Feature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Feature#getName()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Name();

  /**
   * Returns the meta object for the reference '{@link org.typhon.dsls.xtext.typhonDL.Feature#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.typhon.dsls.xtext.typhonDL.Feature#getType()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TyphonDLFactory getTyphonDLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DeploymentModelImpl <em>Deployment Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.DeploymentModelImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDeploymentModel()
     * @generated
     */
    EClass DEPLOYMENT_MODEL = eINSTANCE.getDeploymentModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPLOYMENT_MODEL__ELEMENTS = eINSTANCE.getDeploymentModel_Elements();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.TypeImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.DataTypeImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.PlatformTypeImpl <em>Platform Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.PlatformTypeImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getPlatformType()
     * @generated
     */
    EClass PLATFORM_TYPE = eINSTANCE.getPlatformType();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DBTypeImpl <em>DB Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.DBTypeImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDBType()
     * @generated
     */
    EClass DB_TYPE = eINSTANCE.getDBType();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DeploymentImpl <em>Deployment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.DeploymentImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDeployment()
     * @generated
     */
    EClass DEPLOYMENT = eINSTANCE.getDeployment();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.PlatformImpl <em>Platform</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.PlatformImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getPlatform()
     * @generated
     */
    EClass PLATFORM = eINSTANCE.getPlatform();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLATFORM__TYPE = eINSTANCE.getPlatform_Type();

    /**
     * The meta object literal for the '<em><b>Clusters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLATFORM__CLUSTERS = eINSTANCE.getPlatform_Clusters();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.ClusterImpl <em>Cluster</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.ClusterImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getCluster()
     * @generated
     */
    EClass CLUSTER = eINSTANCE.getCluster();

    /**
     * The meta object literal for the '<em><b>Applications</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLUSTER__APPLICATIONS = eINSTANCE.getCluster_Applications();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.ApplicationImpl <em>Application</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.ApplicationImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getApplication()
     * @generated
     */
    EClass APPLICATION = eINSTANCE.getApplication();

    /**
     * The meta object literal for the '<em><b>Containers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION__CONTAINERS = eINSTANCE.getApplication_Containers();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.ContainerImpl <em>Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.ContainerImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getContainer()
     * @generated
     */
    EClass CONTAINER = eINSTANCE.getContainer();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER__PROPERTIES = eINSTANCE.getContainer_Properties();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER__FEATURES = eINSTANCE.getContainer_Features();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.ServiceImpl <em>Service</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.ServiceImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getService()
     * @generated
     */
    EClass SERVICE = eINSTANCE.getService();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE__FEATURES = eINSTANCE.getService_Features();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.DBServiceImpl <em>DB Service</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.DBServiceImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getDBService()
     * @generated
     */
    EClass DB_SERVICE = eINSTANCE.getDBService();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.BusinessServiceImpl <em>Business Service</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.BusinessServiceImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getBusinessService()
     * @generated
     */
    EClass BUSINESS_SERVICE = eINSTANCE.getBusinessService();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.EntityImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__SUPER_TYPE = eINSTANCE.getEntity_SuperType();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__FEATURES = eINSTANCE.getEntity_Features();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.PropertyImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.EnvListImpl <em>Env List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.EnvListImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getEnvList()
     * @generated
     */
    EClass ENV_LIST = eINSTANCE.getEnvList();

    /**
     * The meta object literal for the '<em><b>Environment Vars</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENV_LIST__ENVIRONMENT_VARS = eINSTANCE.getEnvList_EnvironmentVars();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.AssignmentListImpl <em>Assignment List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.AssignmentListImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getAssignmentList()
     * @generated
     */
    EClass ASSIGNMENT_LIST = eINSTANCE.getAssignmentList();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNMENT_LIST__NAME = eINSTANCE.getAssignmentList_Name();

    /**
     * The meta object literal for the '<em><b>Assignments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT_LIST__ASSIGNMENTS = eINSTANCE.getAssignmentList_Assignments();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.CommaSeparatedAssignmentListImpl <em>Comma Separated Assignment List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.CommaSeparatedAssignmentListImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getCommaSeparatedAssignmentList()
     * @generated
     */
    EClass COMMA_SEPARATED_ASSIGNMENT_LIST = eINSTANCE.getCommaSeparatedAssignmentList();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMA_SEPARATED_ASSIGNMENT_LIST__NAME = eINSTANCE.getCommaSeparatedAssignmentList_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMA_SEPARATED_ASSIGNMENT_LIST__VALUE = eINSTANCE.getCommaSeparatedAssignmentList_Value();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMA_SEPARATED_ASSIGNMENT_LIST__VALUES = eINSTANCE.getCommaSeparatedAssignmentList_Values();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.AssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.AssignmentImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getAssignment()
     * @generated
     */
    EClass ASSIGNMENT = eINSTANCE.getAssignment();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNMENT__NAME = eINSTANCE.getAssignment_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNMENT__VALUE = eINSTANCE.getAssignment_Value();

    /**
     * The meta object literal for the '{@link org.typhon.dsls.xtext.typhonDL.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.typhon.dsls.xtext.typhonDL.impl.FeatureImpl
     * @see org.typhon.dsls.xtext.typhonDL.impl.TyphonDLPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__NAME = eINSTANCE.getFeature_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__TYPE = eINSTANCE.getFeature_Type();

  }

} //TyphonDLPackage
