version: '3.7'

services:
  typhon-polystore-service:
    image: clms/typhon-polystore-api:latest
    ports:
      - target: 8080
        published: 8080
    restart: always
  polystore-ui:
    image: clms/typhon-polystore-ui:latest
    environment:
      API_PORT: 8080
      API_HOST: localhost
    depends_on: 
      - typhon-polystore-service
    ports:
      - target: 4200
        published: 4200
  typhonql-server:
    image: swatengineering/typhonql-server
    ports:
      - target: 7000
    restart: always
