/*
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.typhon.dsls.xtext.typhondl.ui.internal.TyphondlActivator;

public class TyphonDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TyphondlActivator.getInstance().getInjector("org.typhon.dsls.xtext.TyphonDL");
	}

}
