apiVersion: apps/v1
kind: Deployment
metadata:
  name: textwarningdata-deployment
spec:
  selector:
    matchLabels:
      app: textwarningdata-pod
  template:
    metadata:
      labels:
        app: textwarningdata-pod
    spec:
      containers:
        - name: textwarningdata-container
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          ports:
            - containerPort: 27017 
---
kind: Service
apiVersion: v1
metadata:
  name: textwarningdata
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: textwarningdata-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicledatadb-deployment
spec:
  selector:
    matchLabels:
      app: vehicledatadb-pod
  template:
    metadata:
      labels:
        app: vehicledatadb-pod
    spec:
      containers:
        - name: vehicledatadb-container
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 27017 
---
kind: Service
apiVersion: v1
metadata:
  name: vehicledatadb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: vehicledatadb-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclemetadatadb-deployment
spec:
  selector:
    matchLabels:
      app: vehiclemetadatadb-pod
  template:
    metadata:
      labels:
        app: vehiclemetadatadb-pod
    spec:
      containers:
        - name: vehiclemetadatadb-container
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306 
---
kind: Service
apiVersion: v1
metadata:
  name: vehiclemetadatadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: vehiclemetadatadb-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdata-deployment
spec:
  selector:
    matchLabels:
      app: appdata-pod
  template:
    metadata:
      labels:
        app: appdata-pod
    spec:
      containers:
        - name: appdata-container
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306 
---
kind: Service
apiVersion: v1
metadata:
  name: appdata
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: appdata-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polystore-mongo-deployment
spec:
  selector:
    matchLabels:
      app: polystore-mongo-pod
  template:
    metadata:
      labels:
        app: polystore-mongo-pod
    spec:
      containers:
        - name: polystore-mongo-container
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          ports:
            - containerPort: 27017 
          
---
kind: Service
apiVersion: v1
metadata:
  name: polystore-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: polystore-mongo-pod
---
kind: Job
apiVersion: batch/v1
metadata:
  name: insert-models
spec:
  template:
    spec:
      containers:
        - name: insert-models
          image: mongo:latest
          command: ["/bin/sh", "-c"]
          args:
          # wait for polystore-mongo to be ready
            - sleep 20; 
              mongo --host polystore-mongo --port 27017 -u admin -p admin admin --eval 'db.models.insert([{"_id":UUID(), "version":1, "initializedDatabases":false, "initializedConnections":true, "contents":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><typhonDL:DeploymentModel xmi:version=\"2.0\" xmlns:xmi=\"http://www.omg.org/XMI\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:typhonDL=\"http://www.typhon.org/dsls/xtext/TyphonDL\">  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"weatherModel.xmi\"/>  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"TextWarningData.tdl\"/>  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"VehicleDataDB.tdl\"/>  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"VehicleMetadataDB.tdl\"/>  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"AppData.tdl\"/>  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"dbTypes.tdl\"/>  <elements xsi:type=\"typhonDL:ContainerType\" name=\"Docker\"/>  <elements xsi:type=\"typhonDL:ClusterType\" name=\"Kubernetes\"/>  <elements xsi:type=\"typhonDL:PlatformType\" name=\"minikube\"/>  <elements xsi:type=\"typhonDL:Platform\" name=\"platformName\" type=\"//@elements.2\">    <clusters name=\"clusterName\" type=\"//@elements.1\">      <applications name=\"Polystore\">        <containers name=\"TextWarningData\" type=\"//@elements.0\">          <deploys reference=\"//@elements.4\"/>          <ports>            <key_values name=\"target\" value=\"27017\"/>          </ports>        </containers>        <containers name=\"VehicleDataDB\" type=\"//@elements.0\">          <deploys reference=\"//@elements.5\"/>          <ports>            <key_values name=\"target\" value=\"27017\"/>          </ports>        </containers>        <containers name=\"VehicleMetadataDB\" type=\"//@elements.0\">          <deploys reference=\"//@elements.6\"/>          <ports>            <key_values name=\"target\" value=\"3306\"/>          </ports>        </containers>        <containers name=\"AppData\" type=\"//@elements.0\">          <deploys reference=\"//@elements.7\"/>          <ports>            <key_values name=\"target\" value=\"3306\"/>          </ports>        </containers>        <containers name=\"polystore-mongo\" type=\"//@elements.0\">          <deploys reference=\"//@elements.11\"/>          <ports>            <key_values name=\"target\" value=\"27017\"/>          </ports>        </containers>        <containers name=\"typhon-polystore-service\" type=\"//@elements.0\">          <deploys reference=\"//@elements.12\"/>          <ports>            <key_values name=\"target\" value=\"8080\"/>            <key_values name=\"published\" value=\"30061\"/>          </ports>          <properties xsi:type=\"typhonDL:Key_ValueArray\" name=\"entrypoint\">            <values>wait-for-it</values>            <values>polystore-mongo:27017</values>            <values>-t</values>            <values>'60'</values>            <values>--</values>            <values>java</values>            <values>-cp</values>            <values>/app/resources:/app/classes:/app/libs/*</values>            <values>com.clms.typhonapi.Application</values>          </properties>        </containers>        <containers name=\"polystore-ui\" type=\"//@elements.0\">          <deploys reference=\"//@elements.13\"/>          <depends_on reference=\"//@elements.3/@clusters.0/@applications.0/@containers.5\"/>          <ports>            <key_values name=\"target\" value=\"4200\"/>            <key_values name=\"published\" value=\"30075\"/>          </ports>        </containers>        <containers name=\"typhonql-server\">          <deploys reference=\"//@elements.14\"/>          <ports>            <key_values name=\"target\" value=\"7000\"/>          </ports>        </containers>      </applications>    </clusters>  </elements>  <elements xsi:type=\"typhonDL:DB\" name=\"TextWarningData\" type=\"//@elements.8\">    <parameters xsi:type=\"typhonDL:Key_KeyValueList\" name=\"environment\">      <properties xsi:type=\"typhonDL:Key_Values\" name=\"MONGO_INITDB_ROOT_USERNAME\" value=\"admin\"/>      <properties xsi:type=\"typhonDL:Key_Values\" name=\"MONGO_INITDB_ROOT_PASSWORD\" value=\"admin\"/>    </parameters>  </elements>  <elements xsi:type=\"typhonDL:DB\" name=\"VehicleDataDB\" type=\"//@elements.9\">    <parameters xsi:type=\"typhonDL:Key_KeyValueList\" name=\"environment\">      <properties xsi:type=\"typhonDL:Key_Values\" name=\"MONGO_INITDB_ROOT_USERNAME\" value=\"username\"/>      <properties xsi:type=\"typhonDL:Key_Values\" name=\"MONGO_INITDB_ROOT_PASSWORD\" value=\"password\"/>    </parameters>  </elements>  <elements xsi:type=\"typhonDL:DB\" name=\"VehicleMetadataDB\" type=\"//@elements.10\">    <parameters xsi:type=\"typhonDL:Key_KeyValueList\" name=\"environment\">      <properties xsi:type=\"typhonDL:Key_Values\" name=\"MYSQL_ROOT_PASSWORD\" value=\"password\"/>    </parameters>  </elements>  <elements xsi:type=\"typhonDL:DB\" name=\"AppData\" type=\"//@elements.10\">    <parameters xsi:type=\"typhonDL:Key_KeyValueList\" name=\"environment\">      <properties xsi:type=\"typhonDL:Key_Values\" name=\"MYSQL_ROOT_PASSWORD\" value=\"password\"/>    </parameters>  </elements>  <elements xsi:type=\"typhonDL:DBType\" name=\"mongo\">    <image value=\"mongo:latest\"/>  </elements>  <elements xsi:type=\"typhonDL:DBType\" name=\"Mongo\">    <image value=\"mongo:latest\"/>  </elements>  <elements xsi:type=\"typhonDL:DBType\" name=\"MariaDB\">    <image value=\"mariadb:latest\"/>  </elements>  <elements xsi:type=\"typhonDL:DB\" name=\"polystore_db\" type=\"//@elements.8\">    <parameters xsi:type=\"typhonDL:Key_KeyValueList\" name=\"environment\">      <properties xsi:type=\"typhonDL:Key_Values\" name=\"MONGO_INITDB_ROOT_USERNAME\" value=\"admin\"/>      <properties xsi:type=\"typhonDL:Key_Values\" name=\"MONGO_INITDB_ROOT_PASSWORD\" value=\"admin\"/>    </parameters>  </elements>  <elements xsi:type=\"typhonDL:Software\" name=\"polystore_api\">    <image value=\"clms/typhon-polystore-api:latest\"/>  </elements>  <elements xsi:type=\"typhonDL:Software\" name=\"polystore_ui\">    <image value=\"clms/typhon-polystore-ui:latest\"/>    <parameters xsi:type=\"typhonDL:Key_KeyValueList\" name=\"environment\">      <properties xsi:type=\"typhonDL:Key_Values\" name=\"API_PORT\" value=\"&quot;30061&quot;\"/>      <properties xsi:type=\"typhonDL:Key_Values\" name=\"API_HOST\" value=\"&quot;192.168.99.101&quot;\"/>    </parameters>  </elements>  <elements xsi:type=\"typhonDL:Software\" name=\"polystore_ql\">    <image value=\"swatengineering/typhonql-server\"/>  </elements></typhonDL:DeploymentModel>", "type":"DL", "dateReceived":ISODate(), "_class":"com.clms.typhonapi.models.Model" }, {"_id":UUID(), "version":1, "initializedDatabases":false, "initializedConnections":false, "contents":"<?xml version=\"1.0\" encoding=\"ASCII\"?><typhonml:Model xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:typhonml=\"http://org.typhon.dsls.typhonml.sirius\">  <databases xsi:type=\"typhonml:RelationalDB\" name=\"VehicleMetadataDB\">    <tables name=\"VehicleMetadataDB\" entity=\"//@dataTypes.4\">      <indexSpec name=\"metadataIndex\" attributes=\"//@dataTypes.4/@attributes.0\"/>      <idSpec attributes=\"//@dataTypes.4/@attributes.0\"/>    </tables>  </databases>  <databases xsi:type=\"typhonml:DocumentDB\" name=\"VehicleDataDB\">    <collections name=\"VehicleWeatherDataDB\" entity=\"//@dataTypes.3\"/>    <collections name=\"ESPDB\" entity=\"//@dataTypes.5\"/>  </databases>  <databases xsi:type=\"typhonml:RelationalDB\" name=\"AppData\">    <tables name=\"AppDB\" entity=\"//@dataTypes.6\">      <indexSpec name=\"appIndex\" attributes=\"//@dataTypes.6/@attributes.0\"/>    </tables>    <tables name=\"AnalyticsDB\" entity=\"//@dataTypes.9\">      <indexSpec name=\"analyticsIndex\" attributes=\"//@dataTypes.9/@attributes.14\"/>    </tables>  </databases>  <databases xsi:type=\"typhonml:DocumentDB\" name=\"TextWarningData\">    <collections name=\"TextWarningDB\" entity=\"//@dataTypes.8\"/>    <collections name=\"WarningWeatherDB\" entity=\"//@dataTypes.7\"/>  </databases>  <dataTypes xsi:type=\"typhonml:PrimitiveDataType\" name=\"Int\"/>  <dataTypes xsi:type=\"typhonml:PrimitiveDataType\" name=\"String\"/>  <dataTypes xsi:type=\"typhonml:PrimitiveDataType\" name=\"Bool\"/>  <dataTypes xsi:type=\"typhonml:Entity\" name=\"VehicleWeatherData\">    <attributes name=\"VIN\" type=\"//@dataTypes.0\"/>    <attributes name=\"timeStamp\" type=\"//@dataTypes.1\"/>    <attributes name=\"vehicle_position\" type=\"//@dataTypes.1\"/>    <attributes name=\"temperature\" type=\"//@dataTypes.0\"/>    <attributes name=\"rain_Intensity\" type=\"//@dataTypes.0\"/>    <attributes name=\"solar_Intensity\" type=\"//@dataTypes.0\"/>    <relations name=\"metadata\" type=\"//@dataTypes.4\" cardinality=\"one\" isContainment=\"true\"/>  </dataTypes>  <dataTypes xsi:type=\"typhonml:Entity\" name=\"VehicleMetadata\">    <attributes name=\"VIN\" type=\"//@dataTypes.0\"/>    <attributes name=\"brand\" type=\"//@dataTypes.1\"/>    <attributes name=\"model\" type=\"//@dataTypes.1\"/>    <attributes name=\"constr_year\" type=\"//@dataTypes.0\"/>    <attributes name=\"color\" type=\"//@dataTypes.1\"/>    <attributes name=\"t_sensor_h\" type=\"//@dataTypes.0\"/>    <attributes name=\"engine_type\" type=\"//@dataTypes.1\"/>  </dataTypes>  <dataTypes xsi:type=\"typhonml:Entity\" name=\"ESP\">    <attributes name=\"VIN\" type=\"//@dataTypes.0\"/>    <attributes name=\"timeStamp\" type=\"//@dataTypes.1\"/>    <attributes name=\"vehicle_position\" type=\"//@dataTypes.1\"/>    <attributes name=\"esp_edl\" type=\"//@dataTypes.2\"/>    <attributes name=\"esp_idd\" type=\"//@dataTypes.2\"/>    <attributes name=\"esp_abs\" type=\"//@dataTypes.2\"/>    <relations name=\"vweather\" type=\"//@dataTypes.3\" cardinality=\"one\" isContainment=\"true\"/>  </dataTypes>  <dataTypes xsi:type=\"typhonml:Entity\" name=\"App\">    <attributes name=\"VIN\" type=\"//@dataTypes.0\"/>    <attributes name=\"timeStamp\" type=\"//@dataTypes.1\"/>    <attributes name=\"vehicle_position\" type=\"//@dataTypes.1\"/>    <relations name=\"esp\" type=\"//@dataTypes.5\" cardinality=\"zero_many\" isContainment=\"true\"/>    <relations name=\"warnings\" type=\"//@dataTypes.7\" cardinality=\"zero_many\" isContainment=\"true\"/>  </dataTypes>  <dataTypes xsi:type=\"typhonml:Entity\" name=\"WarningWeatherData\">    <attributes name=\"time_start\" type=\"//@dataTypes.1\"/>    <attributes name=\"time_end\" type=\"//@dataTypes.1\"/>    <attributes name=\"warningType\" type=\"//@dataTypes.1\"/>    <attributes name=\"severity\" type=\"//@dataTypes.0\"/>    <attributes name=\"area\" type=\"//@dataTypes.1\"/>  </dataTypes>  <dataTypes xsi:type=\"typhonml:Entity\" name=\"TextWarning\">    <attributes name=\"timeStamp\" type=\"//@dataTypes.1\"/>    <attributes name=\"text\" type=\"//@dataTypes.1\"/>  </dataTypes>  <dataTypes xsi:type=\"typhonml:Entity\" name=\"ExtractedWarning\">    <attributes name=\"ORGANIZATION\" type=\"//@dataTypes.1\"/>    <attributes name=\"WEATHER_EVENT\" type=\"//@dataTypes.1\"/>    <attributes name=\"WEATHER_EVENT_INTENSITY\" type=\"//@dataTypes.1\"/>    <attributes name=\"WEATHER_EVENT_COUNT\" type=\"//@dataTypes.0\"/>    <attributes name=\"LOCATION\" type=\"//@dataTypes.1\"/>    <attributes name=\"WARNING_LEVEL\" type=\"//@dataTypes.0\"/>    <attributes name=\"DAY\" type=\"//@dataTypes.1\"/>    <attributes name=\"DATE\" type=\"//@dataTypes.1\"/>    <attributes name=\"TIME\" type=\"//@dataTypes.1\"/>    <attributes name=\"DISTANCE\" type=\"//@dataTypes.1\"/>    <attributes name=\"DIRECTION\" type=\"//@dataTypes.1\"/>    <attributes name=\"SPEED\" type=\"//@dataTypes.1\"/>    <attributes name=\"SIZE\" type=\"//@dataTypes.1\"/>    <attributes name=\"TEMPERATURE\" type=\"//@dataTypes.0\"/>    <attributes name=\"NUMBER\" type=\"//@dataTypes.0\"/>  </dataTypes></typhonml:Model>", "type":"ML", "dateReceived":ISODate(), "_class":"com.clms.typhonapi.models.Model" }]);';
      restartPolicy: Never
---
