/*
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTyphonDLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.typhon.dsls.xtext.typhonDL.TyphonDLPackage.eINSTANCE);
		return result;
	}
}
