/**
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.typhonDL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.typhon.dsls.xtext.typhonDL.CommaSeparatedAssignmentList;
import org.typhon.dsls.xtext.typhonDL.TyphonDLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comma Separated Assignment List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.typhon.dsls.xtext.typhonDL.impl.CommaSeparatedAssignmentListImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.typhon.dsls.xtext.typhonDL.impl.CommaSeparatedAssignmentListImpl#getValue <em>Value</em>}</li>
 *   <li>{@link org.typhon.dsls.xtext.typhonDL.impl.CommaSeparatedAssignmentListImpl#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CommaSeparatedAssignmentListImpl extends PropertyImpl implements CommaSeparatedAssignmentList
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * The cached value of the '{@link #getValues() <em>Values</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValues()
   * @generated
   * @ordered
   */
  protected EList<String> values;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CommaSeparatedAssignmentListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TyphonDLPackage.Literals.COMMA_SEPARATED_ASSIGNMENT_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getValues()
  {
    if (values == null)
    {
      values = new EDataTypeEList<String>(String.class, this, TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUES);
    }
    return values;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__NAME:
        return getName();
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUE:
        return getValue();
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUES:
        return getValues();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__NAME:
        setName((String)newValue);
        return;
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUE:
        setValue((String)newValue);
        return;
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUES:
        getValues().clear();
        getValues().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__NAME:
        setName(NAME_EDEFAULT);
        return;
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUES:
        getValues().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
      case TyphonDLPackage.COMMA_SEPARATED_ASSIGNMENT_LIST__VALUES:
        return values != null && !values.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", value: ");
    result.append(value);
    result.append(", values: ");
    result.append(values);
    result.append(')');
    return result.toString();
  }

} //CommaSeparatedAssignmentListImpl
