/**
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.typhonDL.impl;

import org.eclipse.emf.ecore.EClass;

import org.typhon.dsls.xtext.typhonDL.DBType;
import org.typhon.dsls.xtext.typhonDL.TyphonDLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>DB Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DBTypeImpl extends TypeImpl implements DBType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DBTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TyphonDLPackage.Literals.DB_TYPE;
  }

} //DBTypeImpl
