/**
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.typhonDL.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.typhon.dsls.xtext.typhonDL.EnvList;
import org.typhon.dsls.xtext.typhonDL.TyphonDLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Env List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.typhon.dsls.xtext.typhonDL.impl.EnvListImpl#getEnvironmentVars <em>Environment Vars</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnvListImpl extends PropertyImpl implements EnvList
{
  /**
   * The cached value of the '{@link #getEnvironmentVars() <em>Environment Vars</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnvironmentVars()
   * @generated
   * @ordered
   */
  protected EList<String> environmentVars;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnvListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TyphonDLPackage.Literals.ENV_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getEnvironmentVars()
  {
    if (environmentVars == null)
    {
      environmentVars = new EDataTypeEList<String>(String.class, this, TyphonDLPackage.ENV_LIST__ENVIRONMENT_VARS);
    }
    return environmentVars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TyphonDLPackage.ENV_LIST__ENVIRONMENT_VARS:
        return getEnvironmentVars();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TyphonDLPackage.ENV_LIST__ENVIRONMENT_VARS:
        getEnvironmentVars().clear();
        getEnvironmentVars().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TyphonDLPackage.ENV_LIST__ENVIRONMENT_VARS:
        getEnvironmentVars().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TyphonDLPackage.ENV_LIST__ENVIRONMENT_VARS:
        return environmentVars != null && !environmentVars.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (environmentVars: ");
    result.append(environmentVars);
    result.append(')');
    return result.toString();
  }

} //EnvListImpl
