/*
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.typhon.dsls.xtext.parser.antlr.internal.InternalTyphonDLParser;
import org.typhon.dsls.xtext.services.TyphonDLGrammarAccess;

public class TyphonDLParser extends AbstractAntlrParser {

	@Inject
	private TyphonDLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTyphonDLParser createParser(XtextTokenStream stream) {
		return new InternalTyphonDLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DeploymentModel";
	}

	public TyphonDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TyphonDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
