/*
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TyphonDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/typhon/dsls/xtext/parser/antlr/internal/InternalTyphonDL.tokens");
	}
}
