version: '3.7'

services:
  VehicleDataDB:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - target: 27017
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: '0.25'
        reservations:
          memory: 20M
          cpus: '0.1'
  AppData:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - target: 3306
  VehicleMetadataDB:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - target: 3306
  TextWarningData:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - target: 27017
  polystore-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - target: 27017
    volumes:
      - ./models/:/docker-entrypoint-initdb.d
