/*
 * generated by Xtext 2.15.0
 */
package org.typhon.dsls.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTyphonDLScopeProvider extends DelegatingScopeProvider {
}
