version: '3.7'

networks:
  typhon:
services:
  polystore_api:
    image: clms/typhon-polystore-api:latest
    restart: always
    hostname: polystore_api
    depends_on: 
      - polystoredb
    container_name: typhonml.polystore.service
    ports:
      - 8080:8080
    volumes:
      - ./models:/models
  polystore_ui:
    image: clms/typhon-polystore-ui:latest
    restart: always
    hostname: polystore_ui
    depends_on: 
      - polystore_api
    container_name: polystore.ui
    ports:
      - 4200:4200
  polystoredb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: polystore.mongo
    ports:
      - 27017:27017
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - typhon
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    depends_on: 
      - zookeeper
    networks:
      - typhon
    build: .
    container_name: kafka
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: PLAINTEXT://:29092, PLAINTEXT://:29093, PLAINTEXT_HOST://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT://kafka:29093, PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  TextWarningData:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
  AppData:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
