version: '3.5'

services: 
mariadb:
	image: gitlab.atb-bremen.de:5555/atb/docker-base-images/mariadb:10.3.7-utf8
	environment:
	- MYSQL_ROOT_PASSWORD: geheim
	- MYSQL_DATABASE: locman
	- MYSQL_USER: locman
	- MYSQL_PASSWORD: geheim
	volumes: /opt/locman-staging/db:/var/lib/mysql
	networks: locman
locman:
	image: gitlab.atb-bremen.de:5555/europool/locman/location-mgmt-datastore:0.2.0-SNAPSHOT
	entrypoint: [
	'/maven/wait-for.sh',
	'mariadb:3306',
	'-t',
	'60',
	'--',
	'java',
	'-Djava.security.egd=file:/dev/./urandom',
	'-jar',
	'/maven/location-mgmt-datastore-0.2.0-SNAPSHOT.jar',
	'--spring.profiles.active=default,staging'
	]
	environment:
	- MARIADB_HOST: mariadb
	- MARIADB_PORT: someportnumer
	- MARIADB_USER: locman
	- MARIADB_PASSWORD: geheim
	ports: 8086:8086
	networks: locman
