apiVersion: v1
kind: Service
metadata:
  name: polystore-api
  labels:
    app: polystore-api
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: polystore-api-pod