apiVersion: v1
kind: Service
metadata:
  name: polystore-api-db
  labels:
    app: polystore-api-db
spec:
  type: NodePort
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: polystore-db-pod