apiVersion: v1
kind: Service
metadata:
  name: polystore-ui
  labels:
    app: polystore-ui
spec:
  type: NodePort
  ports:
    - name: "4200"
      port: 4200
      targetPort: 4200
  selector:
    app: polystore-ui-pod